version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - https_proxy=http://192.168.0.104:7890
        - http_proxy=http://192.168.0.104:7890
        - all_proxy=socks5://192.168.0.104:7890
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_WS_URL=ws://localhost:3001
      - https_proxy=http://192.168.0.104:7890
      - http_proxy=http://192.168.0.104:7890
      - all_proxy=socks5://192.168.0.104:7890
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - aigame-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - https_proxy=http://192.168.0.104:7890
        - http_proxy=http://192.168.0.104:7890
        - all_proxy=socks5://192.168.0.104:7890
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/aigame
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - https_proxy=http://192.168.0.104:7890
      - http_proxy=http://192.168.0.104:7890
      - all_proxy=socks5://192.168.0.104:7890
    depends_on:
      - mongodb
      - neo4j
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: yarn start:dev
    networks:
      - aigame-network

  mongodb:
    image: mongo:6
    container_name: aigame-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=aigame
    networks:
      - aigame-network

  neo4j:
    image: neo4j:5
    container_name: aigame-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - aigame-network

  redis:
    image: redis:7-alpine
    container_name: aigame-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - aigame-network

volumes:
  mongodb_data:
  neo4j_data:
  neo4j_logs:
  redis_data:

networks:
  aigame-network:
    driver: bridge
